### ISSUE TITLE
cannot use external editor in scriptrunner 3 (using win. 8.1, qgis 3.4.0 (OSGEO4W64) and python 37)

### ISSUE THREAD

**Issue by damidb** [g-sherman/Script-Runner#7]
hello mr, mrs,

following message when trying to edit testfile.py in scriptrunner 3 plugin:
*******
Traceback (most recent call last):
  File "C:/Users/myname/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\scriptrunner3\scriptrunner.py", line 848, in edit_script
str(self.custom_editor))
pywintypes.error: (123, 'GetShortPathNameW', 'The filename, directory name, or volume label syntax is incorrect.')
********
(did not have that problem with qgis standalone 2.7 "las palmas")
I case you respond: please notice I'm not an IT-specialist just a user 
trying to do some exercises in python with qgis - so keep is easy if possible  please 
- or explain every single step of the solution (no abbrevations/jargon if possible) : thanks a lot !!!

**Comment by g-sherman** [comment]
Sounds like it can't find your external editor. What have you entered for the full path to the editor?

**Comment by damidb** [comment]
I entered the following path for my external editor:
C:\Windows\System32
but it's working after changing in C:\Program Files (x86)\LibreOffice 4\program\swriter.exe
don't ask me why...
sorry for late reply.. busy..

**Comment by ytreka3** [comment]
Hi, I tried to set a default external editor in Scriptrunner 3, using the following steps: 
click on menu plugins in Qgis
click on scriptrunner and scriptrunner 3 icon
click on gear icon
in general options, click on "Edit scripts using" checkbox and select the path of Visual Studio Code
But the the program at this point advise me in this way: 

TypeError: setText(self, str): argument 1 has unexpected type 'tuple' 
Traceback (most recent call last):
  File "C:\Users/Salvo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\scriptrunner3\preferences_dialog.py", line 94, in editor_path
    self.ui.leCustomEditorPath.setText(self.editor_path)
TypeError: setText(self, str): argument 1 has unexpected type 'tuple'

Why this error happens? Thank you
